trigger:
  branches:
    include:
    - master
    - release-*
  tags:
    include:
      - "*"

jobs:
- job: Build
  strategy:
    matrix:
      ubuntu_18:
        imageName: 'ubuntu-18.04'
        python.version: '3.x'
        CXX: g++
        BUILD_PYTHON_API: ON
        BUILD_SPARK_API: ON
      mac:
        imageName: 'macOS-10.14'
        python.version: '3.7'
        CXX: clang++
        SDKROOT: '/Applications/Xcode_10.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk'

  pool:
    vmImage: $(imageName)
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - template: ci/azure-linux_mac.yml

- job: Docker
  dependsOn: Build
  pool:
    vmImage: 'ubuntu-18.04'
  condition: |
    or(
      eq(variables['build.sourceBranch'], 'refs/heads/master'),
      startsWith(variables['build.sourceBranch'], 'refs/tags')
    )

  strategy:
    matrix:
      cli:
        dockerfile: docker/Dockerfile-cli
        repository: tiledb/tiledbvcf-cli
        context: .
      python:
        dockerfile: docker/Dockerfile-py
        repository: tiledb/tiledbvcf-py
        context: .
      # dask:
      #   dockerfile: docker/Dockerfile-dask-py
      #   repository: tiledb/tiledbvcf-dask
      #   context: .

  steps:
  - template: ci/build-images.yml
