trigger:
  branches:
    include:
    - master
    - release-*
    - aw/azure-ci-test
  tags:
    include:
      - "*"

jobs:
- job: Build
  strategy:
    matrix:
      ubuntu_18:
        imageName: 'ubuntu-18.04'
        python.version: '3.x'
        CXX: g++
        BUILD_PYTHON_API: ON
        BUILD_SPARK_API: ON
#      macOS:
#        imageName: 'macOS-10.13'
#        CXX: clang++

  pool:
    vmImage: $(imageName)
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - template: ci/azure-linux_mac.yml

- job: Docker
  dependsOn: Build
  condition: |
    or(
      eq(variables['build.sourceBranch'], 'refs/heads/aw/azure-ci-test'),
      startsWith(variables['build.sourceBranch'], 'refs/tags')
    )

  strategy:
    matrix:
      cli:
        dockerfile: docker/Dockerfile-cli
        repository: tiledb/tiledbvcf-cli
        context: libtiledbvcf
      # python:
      #   dockerfile: docker/Dockerfile-py
      #   repository: tiledb/tiledbvcf-py
      #   context: .
      # dask:
      #   dockerfile: docker/Dockerfile-dask-py
      #   repository: tiledb/tiledbvcf-dask
      #   context: .

  steps:
  - template: ci/build-images.yml
