trigger:
  branches:
    include:
    - master
    - release-*
    - refs/tags/*

variables:
  isRefTag: $[startsWith(variables['Build.SourceBranch'], 'refs/tags')]
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

stages:
  - stage: CI
    condition: eq(variables.isRefTag, false)
    jobs:
    - job: Build
      strategy:
        matrix:
          linux:
            imageName: 'ubuntu-18.04'
            python.version: '3.x'
            CXX: g++
            BUILD_PYTHON_API: ON
            BUILD_SPARK_API: ON
          mac:
            imageName: 'macOS-10.14'
            python.version: '3.7'
            CXX: clang++
            BUILD_PYTHON_API: ON
            BUILD_SPARK_API: ON
            SDKROOT: '/Applications/Xcode_10.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk'

      pool:
        vmImage: $(imageName)
      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: 'x64'
      - script: printenv
        displayName: 'Print Env'
      # - template: ci/azure-linux_mac.yml
      - bash: exit 1

  - stage: Docker
    condition: or(succeeded(), eq(variables.isRefTag, true))
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-18.04'
        strategy:
          matrix:
            cli:
              dockerfile: docker/Dockerfile-cli
              repository: aaronwolen/dev-vcf-cli
              context: .
            python:
              dockerfile: docker/Dockerfile-py
              repository: aaronwolen/dev-vcf-py
              context: .
            # dask:
            #   dockerfile: docker/Dockerfile-dask-py
            #   repository: tiledb/tiledbvcf-dask
            #   context: .
        steps:
          - script: exit 0
        # - template: ci/build-images.yml

  - stage: BuildNativeLibs
    condition: and(succeeded(), or(eq(variables.isMaster, true), eq(variables.isRefTag, true)))
    jobs:
      - job: Linux_OSX
        strategy:
          matrix:
            linux:
              imageName: 'ubuntu-18.04'
              python.version: '3.x'
              CXX: g++
              BUILD_PYTHON_API: ON
              BUILD_SPARK_API: ON
            mac:
              imageName: 'macOS-10.14'
              python.version: '3.7'
              CXX: clang++
              BUILD_PYTHON_API: ON
              BUILD_SPARK_API: ON
              SDKROOT: '/Applications/Xcode_10.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk'

        pool:
          vmImage: $(imageName)
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(python.version)'
              architecture: 'x64'
          - script: printenv
            displayName: 'Print Env'
          - template: ci/native_libs-linux_osx.yml

  - stage: GitHubRelease
    condition: eq(variables.isRefTag, true)
    jobs:
      - job: All_OS
        strategy:
          matrix:
            ubuntu_18:
              imageName: 'ubuntu-18.04'
        pool:
          vmImage: $(imageName)

        steps:
          - download: current
            patterns: '**/*.tar.gz'

          - bash: |
              unset SYSTEM
              set +e

              mv ../libraries/* .

              mkdir lib

              for arch in $(ls | grep .tar.gz)
              do
              tar -xf $arch
              done

              # OSX
              mv *.dylib lib

              # Linux
              mv *.so lib

              cd ./apis/spark

              ./gradlew assemble
              ./gradlew shadowJar

              mkdir $BUILD_BINARIESDIRECTORY/jars
              cp ./build/libs/*.jar $BUILD_BINARIESDIRECTORY/jars

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(Build.BinariesDirectory)'
              includeRootFolder: false
              archiveType: 'tar' # Options: zip, 7z, tar, wim
              tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
              archiveFile: $(Build.ArtifactStagingDirectory)/tiledb-vcf-jar-$(Build.SourceBranchName).tar.gz
              replaceExistingArchive: true
              verbose: true # Optional
            condition: succeeded()

          - task: PublishBuildArtifacts@1
            inputs:
              pathtoPublish: $(Build.ArtifactStagingDirectory)/tiledb-vcf-jar-$(Build.SourceBranchName).tar.gz
              artifactName: libraries
            condition: succeeded()

          - task: GithubRelease@0
            displayName: 'GitHub Release'
            inputs:
              gitHubConnection: github_aaronwolen
              repositoryName: aaronwolen/TileDB-VCF
              tag: $(Build.SourceBranchName)
              action: "edit"
              assets: $(Build.BinariesDirectory)/jars/*.jar
